package net.explorviz.persistence.repository;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import net.explorviz.persistence.ogm.Contributor;
import net.explorviz.persistence.ogm.ResourceAnnotation;
import net.explorviz.persistence.ogm.ResourceVersion;
import net.explorviz.persistence.ogm.TrackableResource;
import org.neo4j.ogm.session.Session;
import org.neo4j.ogm.session.SessionFactory;

@ApplicationScoped
public class TrackableResourceRepository {

  @Inject SessionFactory sessionFactory;

  public <T extends TrackableResource> Optional<T> findByNumber(
      final Session session,
      final Class<T> type,
      final Integer number,
      final String repoName,
      final String tokenId) {
    final T resource =
        session.queryForObject(
            type,
            """
            MATCH (:Landscape {tokenId: $tokenId})
              -[:CONTAINS]->(:Repository {name: $repoName})
              -[:CONTAINS]->(t:%s {number: $number})
            RETURN t;
            """
                .formatted(type.getSimpleName()),
            Map.of("tokenId", tokenId, "repoName", repoName, "number", number));

    if (resource != null) {
      return Optional.of(session.load(type, resource.getId(), 2));
    }
    return Optional.empty();
  }

  /** Finds all trackableResources of a given type authored by a specific Contributor. */
  public <T extends TrackableResource> Set<T> findAllByContributor(
      final Session session,
      final Class<T> type,
      final String repoName,
      final String tokenId,
      final Contributor contributor) {

    final String cypher =
        """
        MATCH (:Landscape {tokenId: $tokenId})
          -[:CONTAINS]->(:Repository {name: $repoName})
          -[:CONTAINS]->(t:%s)-[:HAS_VERSION]->(:ResourceVersion)-[:CREATED_BY]->(c:Contributor {gitUsername: $contributorName})
        RETURN DISTINCT t;
        """
            .formatted(type.getSimpleName());

    final Map<String, Object> params =
        Map.of(
            "tokenId", tokenId,
            "repoName", repoName,
            "contributorName", contributor.getGitUsername());

    final Iterable<T> results = session.query(type, cypher, params);

    final Set<T> resultSet = new HashSet<>();
    results.forEach(resultSet::add);

    return resultSet;
  }

  /**
   * Add a new trackableResourceAnnotation to the database and handles adding resourceVersion
   * objects generated by it and inserting them into the chain of already persisted versions.
   */
  public <T extends TrackableResource> ResourceAnnotation addAnnotationEvent(
      final Session session,
      final T trackableResource,
      final ResourceAnnotation annotation,
      final ResourceVersion resourceVersion) {

    if (trackableResource.getId() == null) {
      session.save(trackableResource, 0);
    }

    if (resourceVersion.getCreationDate() == null) {
      resourceVersion.setCreationDate(annotation.getTimestamp());
    }

    final long timestamp = resourceVersion.getCreationDate().toEpochMilli();

    final ResourceVersion predecessorVersion =
        findPredecessor(session, trackableResource.getId(), timestamp);

    final ResourceVersion successorVersion =
        findSuccessor(session, trackableResource.getId(), timestamp);

    linkNewVersion(resourceVersion, predecessorVersion, annotation, trackableResource);

    // update successor relation in case of out of order arrival
    if (successorVersion != null) {
      relinkSuccessor(session, resourceVersion, successorVersion);
    } else {
      updateResourceToLatest(session, trackableResource, resourceVersion);
    }

    session.save(annotation, 2);
    trackableResource.addVersion(resourceVersion);
    resourceVersion.setResource(trackableResource);
    session.save(trackableResource, 1);

    return annotation;
  }

  private ResourceVersion findPredecessor(
      final Session session, final Long resourceId, final long timestamp) {
    return session.queryForObject(
        ResourceVersion.class,
        """
        MATCH (t)-[:HAS_VERSION]->(v:ResourceVersion)
        WHERE id(t) = $resourceId AND v.creationDate < $newDate
        RETURN v ORDER BY v.creationDate DESC LIMIT 1
        """,
        Map.of("resourceId", resourceId, "newDate", timestamp));
  }

  private ResourceVersion findSuccessor(
      final Session session, final Long resourceId, final long timestamp) {
    return session.queryForObject(
        ResourceVersion.class,
        """
        MATCH (t)-[:HAS_VERSION]->(v:ResourceVersion)
        WHERE id(t) = $resourceId AND v.creationDate > $newDate
        RETURN v ORDER BY v.creationDate ASC LIMIT 1
        """,
        Map.of("resourceId", resourceId, "newDate", timestamp));
  }

  private void linkNewVersion(
      final ResourceVersion newVersion,
      final ResourceVersion predecessorVersion,
      final ResourceAnnotation annotation,
      final TrackableResource trackableResource) {

    annotation.setUsedResource(predecessorVersion);
    annotation.setGeneratedResourceVersion(newVersion);
    newVersion.setGeneratedBy(annotation);
    newVersion.setResource(trackableResource);

    if (annotation.getAssociatedContributor() != null) {
      newVersion.setCreatedBy(annotation.getAssociatedContributor());
    }

    if (predecessorVersion != null) {
      newVersion.setDerivedFrom(predecessorVersion);
    }
  }

  private void relinkSuccessor(
      final Session session,
      final ResourceVersion newVersion,
      final ResourceVersion successorVersion) {
    successorVersion.setDerivedFrom(newVersion);

    final ResourceAnnotation successorAnnotation =
        session.queryForObject(
            ResourceAnnotation.class,
            "MATCH (a:ResourceAnnotation)-[:GENERATES]->(v:ResourceVersion) WHERE id(v) = $succId"
                + " RETURN a",
            Map.of("succId", successorVersion.getId()));

    if (successorAnnotation != null) {
      successorAnnotation.setUsedResource(newVersion);
      session.save(successorAnnotation, 1);
    }
    session.save(successorVersion, 1);
  }

  private void updateResourceToLatest(
      final Session session,
      final TrackableResource trackableResource,
      final ResourceVersion newVersion) {
    if (newVersion.getState() != null) {
      trackableResource.setState(newVersion.getState().name());
    }
    trackableResource.setTitle(newVersion.getTitle());
    if (newVersion.getLabels() != null) {
      trackableResource.setLabels(new HashSet<>(newVersion.getLabels()));
    }
    session.save(trackableResource, 0);
  }

  public <T extends TrackableResource> T getOrCreateTrackableResource(
      final Session session,
      final Class<T> type,
      final Integer number,
      final String repoName,
      final String tokenId) {
    return findByNumber(session, type, number, repoName, tokenId)
        .orElseGet(
            () -> {
              try {
                final T resource = type.getDeclaredConstructor().newInstance();
                resource.setNumber(number);
                return resource;
              } catch (ReflectiveOperationException e) {
                throw new IllegalArgumentException(
                    "Could not instantiate TrackableResource of type: " + type.getSimpleName(), e);
              }
            });
  }
}
