CREATE CONSTRAINT landscape_token_id IF NOT EXISTS FOR (l:Landscape) REQUIRE l.tokenId IS UNIQUE;
CREATE INDEX directory_name IF NOT EXISTS FOR (d:Directory) ON (d.name);
CREATE INDEX file_revision_hash_name IF NOT EXISTS FOR (f:FileRevision) ON (f.hash, f.name);
CREATE INDEX file_revision_repo_file_path_hash IF NOT EXISTS FOR (f:FileRevision) ON (f.repoName, f.filePath, f.hash);
CREATE INDEX file_revision_repo_file_path IF NOT EXISTS FOR (f:FileRevision) ON (f.repoName, f.filePath);
CREATE INDEX file_revision_repo_name IF NOT EXISTS FOR (f:FileRevision) ON (f.repoName, f.name);
CREATE INDEX file_revision_lookup_key IF NOT EXISTS FOR (f:FileRevision) ON (f.lookupKey);
CREATE INDEX function_name IF NOT EXISTS FOR (f:Function) ON (f.name);
CREATE INDEX commit_hash IF NOT EXISTS FOR (c:Commit) ON (c.hash);
CREATE INDEX commit_commit_date IF NOT EXISTS FOR (c:Commit) ON (c.commitDate);
CREATE INDEX commit_has_accumulated_metrics IF NOT EXISTS FOR (c:Commit) ON (c.hasAccumulatedMetrics);
CREATE INDEX file_revision_has_file_data IF NOT EXISTS FOR (f:FileRevision) ON (f.hasFileData);
